### PR TITLE
`activerecord v5` support

### LINKED ISSUE #71: Fix tests for Rails 5
See #62: [build](https://travis-ci.org/ActsAsParanoid/acts_as_paranoid/jobs/178866110)

```
1) Failure:

ValidatesUniquenessTest#test_should_validate_without_deleted [/home/travis/build/ActsAsParanoid/acts_as_paranoid/test/test_validations.rb:16]:

Expected true to not be truthy.
```

### PR DESCRIPTION
**Pull request by itsmechlark**
- [x] Test using rails stable release & edge
- [x] Fix #71 using #83 
- [x] `activerecord v5.1` support, #78

### CODE REVIEW

**Comment by itsmechlark** [comment]
In `activerecord 5.1` callback under after_commit during destroy is not run since it does not exist in the `_callbacks`.

**Comment by bhgames** [comment]
@itsmechlark I need this for my 5.1 rails app. Is this branch stable enough to go with?

**Comment by bplexico** [comment]
@zzak can you merge?

**Comment by zzak** [comment]
:bow: thank you! should we release this? i wonder if things break w/ v5.2

**Comment by itsmechlark** [comment]
You're welcome, @zzak! Yes, it will help those who need to upgrade to `rails v5`. Right now, the test against `rails` edge passed. BTW, thank you for merging this one. :)

**Pull request merged**
