### PR TITLE
Do not load `ActiveRecord` too early

### PR DESCRIPTION
**Pull request by fatkodima**
The problem is well described in https://github.com/rails/rails/issues/46567.
We are currently hitting this when upgrading to rails 7.2.

### CODE REVIEW

**Comment by mvz** [comment]
Thanks @fatkodima, this looks good. Can you please rebase on current master which now includes #329?

**Comment by fatkodima** [comment]
Rebased.

**Comment by mvz** [comment]
@fatkodima thanks!

**Comment by mvz** [comment]
@fatkodima I have just released acts_as_paranoid version 0.10.0 which includes this fix.

**Pull request merged**
