### PR TITLE
Compatibility with Rails 5

### PR DESCRIPTION
**Pull request by sjke**
Full compatibility with Rails 5

### CODE REVIEW

**Comment by zzak** [comment]
Ahh, tests failed because we're still supporting Ruby 1.9.3, which Rails 5 doesn't.

In this case we probably have to wait and release a Rails 5 compatible version after dropping support for old rubies.

This means a version bump.

Before we can do that I need to ship Rails 4.1 and 4.2 compatible release.

In any case, thank you for working on this!!! <3 <3

**Comment by szymonbaranowski** [comment]
Any progress with this one @zzak ?

**Comment by zzak** [comment]
@sjke @szymonbaranowski This will need a rebase <3

**Comment by zzak** [comment]
I tried manually rebasing this patch, and OK to merge for the 0.5.0 release -- but it seems the tests from #40 are now failing with Rails 5.

**Pull request merged**
