### PR TITLE
Make compatible with rails 5.2.0.rc1

### PR DESCRIPTION
**Pull request by pyromaniackeca**
Fix for #94 . I'm not sure if there is a better way to approach this.

### CODE REVIEW

**Comment by mvz** [comment]
The Travis build is currently missing an activerecord 5.2 build. I'm going to build this change locally and see if everything passes.

**Comment by pyromaniackeca** [comment]
Great, thanks. I'd be happy to help push this all the way when the Travis config is updated.

**Comment by mvz** [comment]
Thanks @pyromaniackeca. I've updated the Travis configuration accordingly. The Rails 5.2 builds are still allowed failures for now, but at least we can now see once they start succeeding.

**Comment by goravbhootra** [comment]
@mvz any chances of this getting merged soon? Thanks

**Comment by mvz** [comment]
@goravbhootra thanks for the reminder, I'll look at it today.

**Comment by pyromaniackeca** [comment]
Sorry guys, unfortunately I haven't had a chance to work on this for a while now. What I managed to find out is that one of the test models fails to persist when provided with a `deleted_at` upon creation. Still not completely sure why.

**Comment by goravbhootra** [comment]
@mvz @pyromaniackeca could we still merge this and raise an issue for the case where it is failing marking it as bug? Without this PR, its a showstopper for migration to Rails 5.2.

**Comment by mvz** [comment]
@goravbhootra I'm worried that things will just not work on Rails 5.2. A release that's compatible with 5.1 would already be very useful I guess.

**Comment by mvz** [comment]
I'm taking a stab at investigating and hopefully fixing the remaining failing tests today.

**Comment by mvz** [comment]
I'm going to merge this one in to make applying additional fixes easier. **WARNING** This does not mean that things are working properly with Rails 5.2. In particular, `#delete` will fully destroy a paranoid record.

**Comment by mvz** [comment]
@pyromaniackeca I fixed the remaining test failures in #106.

**Comment by pyromaniackeca** [comment]
@mvz Great, thank you for the help.

**Pull request merged**
