### PR TITLE
ActiveRecord queries with includes now respect :with_deleted => true

### PR DESCRIPTION
**Pull request by pelargir**
This fixes issue #17 by ensuring :with_deleted => true is respected when using #includes and #joins in association queries. Hat tip to @tkupari for the original fix in goncalossilva/acts_as_paranoid#115

### CODE REVIEW

**Comment by zzak** [comment]
@pelargir The build failed, could you look into it?

**Comment by pelargir** [comment]
@zzak There.

**Comment by alexggordon** [comment]
@zzak @pelargir what's the status on this? Can we get this merged?

**Comment by pelargir** [comment]
@alexggordon still ready to be merged as far as I'm concerned.

**Comment by vellotis** [comment]
Works great! Regards @pelargir 

@zzak I know this project isn't actively used any more. But this PR gives a great improvement. Could you please at least merge it? Publishing a gem would also be welcome.

**Comment by zzak** [comment]
@vellotis Thanks for the feedback!

I'm hoping to get around to this soon, sorry for such a long delay~

**Comment by zzak** [comment]
Needs a rebase

**Comment by zzak** [comment]
@pelargir Thank you!!

@vellotis Merged!

Thanks everyone for your patience <3

**Comment by vellotis** [comment]
My best regards! @zzak

**Comment by btrscott** [comment]
Doesn't seem to be working for me.  Still including the: AND driver.deleted_at IS NULL in the sql that filters out the records when the associated field is deleted

Using 
belongs_to :driver, with_deleted: true

Want to bring up the parent record even though the driver is deleted.

Can anyone confirm the fix works for them?  Using 0.5.0 gem.

**Comment by btrscott** [comment]
@zzak This does not seem to be working for me still. Are you sure this is fixed?

**Pull request merged**
