### PR TITLE
You can use this method to achieve soft deletion with ActiveStorage i…

### PR DESCRIPTION
**Pull request by TanishqGupta12**
…n README.md

I am asking how to use ActiveStorage with acts_as_paranoid

### CODE REVIEW

**Comment by mvz** [comment]
Hi @TanishqGupta12 have you tried this method?

**Comment by TanishqGupta12** [comment]
> Hi @TanishqGupta12 have you tried this method?

yesss ... i tried

**Comment by TanishqGupta12** [comment]
you can merge please message me

**Comment by mvz** [comment]
> I am asking how to use ActiveStorage with acts_as_paranoid

Who are you asking?

**Comment by mvz** [comment]
Closing this since:
- It looks like a pasted ChatGPT answer
- The text does not fit where it has been pasted in the README
- There are no tests that exercise the proposed solution, and I'm pretty sure it won't work in many cases

**Pull request closed without merging**
