### PR TITLE
Call acts_as_paranoid in ApplicationRecord

### PR DESCRIPTION
**Pull request by tofoli**
In the ApplicationRecord `table_name` does not exist

### CODE REVIEW

**Comment by zzak** [comment]
@tofoli Could you explain this change? It would help if someone else can confirm, tbh I don't follow Rails development so closely these days

**Comment by tofoli** [comment]
When using `acts_as_paranoid` in the` ApplicationRecord` class,  `self.table_name` does not exist, so setting in the` acts_as_paranoid` method does not work.

```ruby
self.paranoid_column_reference = "#{self.table_name}.#{paranoid_configuration[:column]}"
```

What I did was create the `paranoid_column_reference` method that is executed by the child classes where there is value in` self.table_name`

**Comment by zzak** [comment]
@tofoli I'm not sure we need intend to support `ApplicationRecord` level interface.. I'll need more time to think about it. In any case, this should include some test coverage if accepted.

**Comment by mvz** [comment]
This looks similar to #117.

**Comment by mvz** [comment]
@tofoli this should be covered by #131, which was released in 0.6.2. Please let me know if that doesn't work for you.

**Pull request closed without merging**
