### PR TITLE
Try to fix decrement_counters

### PR DESCRIPTION
**Pull request by paveldruzyak**
related to #39

### CODE REVIEW

**Comment by jthibeaux** [comment]
Just ran across this problem.  Would be great to get this merged.

**Comment by malachaifrazier** [comment]
:+1:

**Comment by sevaorlov** [comment]
I have the same problem. I don't like that some code is just copied from ActiveRecord, but I do not see any other way right now.

**Comment by zzak** [comment]
@paveldruzyak Any way you can take a look at this affecting Rails 5?

**Comment by paveldruzyak** [comment]
@zzak sorry, but no

**Comment by zzak** [comment]
@paveldruzyak Then I'm going to revert this patch, until a fix can be made which supports Rails 5.

Thank you for your contribution!

**Pull request merged**
